#pragma config(Sensor, in1,    powerExpander,  sensorAnalog)
#pragma config(Sensor, dgtl1,  quadLeft,       sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  LEDGreen,       sensorLEDtoVCC)
#pragma config(Sensor, dgtl6,  LEDYellow,      sensorLEDtoVCC)
#pragma config(Sensor, dgtl7,  LEDRed,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl8,  jumper,         sensorTouch)
#pragma config(Sensor, dgtl11, quadRight,      sensorQuadEncoder)
#pragma config(Motor,  port1,           claw,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           leftCLift,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           leftMGLift,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           drvTopLeft,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           drvBottomLeft, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           drvBottomRight, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           drvTopRight,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           rightMGLift,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rightCLift,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
  AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

void basicDrive()
{
	motor[drvTopRight] = ((vexRT[Ch4]*-1) - (vexRT[Ch3]*-1));
	motor[drvTopLeft] = ((vexRT[Ch4]*-1) + (vexRT[Ch3]*-1));
	motor[drvBottomRight] = ((vexRT[Ch4]*-1) - (vexRT[Ch3]*-1));
	motor[drvBottomLeft] = ((vexRT[Ch4]*-1) + (vexRT[Ch3]*-1));
}

task usercontrol()
{
  // User control code here, inside the loop

  while (true)
  {
		basicDrive();
  }
}
